scrape_configs:
  - job_name: application_admin_service
    static_configs:
      - targets: ["http://192.168.0.105:8086"]
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: victoria-metrics
      client_secret: i1yi2jFvF44bT5Hy68CTjK0TjJAoCkGt
      token_url: http://192.168.0.105:8084/realms/application_keycloak/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials
  - job_name: application_catalogue_service
    static_configs:
      - targets: ["http://192.168.0.105:8081"]
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: victoria-metrics
      client_secret: i1yi2jFvF44bT5Hy68CTjK0TjJAoCkGt
      token_url: http://192.168.0.105:8084/realms/application_keycloak/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials
  - job_name: application_customer_module
    static_configs:
      - targets: ["http://192.168.0.105:8083"]
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: victoria-metrics
      client_secret: i1yi2jFvF44bT5Hy68CTjK0TjJAoCkGt
      token_url: http://192.168.0.105:8084/realms/application_keycloak/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials
  - job_name: application_feedback_module
    static_configs:
      - targets: ["http://192.168.0.105:8085"]
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: victoria-metrics
      client_secret: i1yi2jFvF44bT5Hy68CTjK0TjJAoCkGt
      token_url: http://192.168.0.105:8084/realms/application_keycloak/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials
  - job_name: application_manager_module
    static_configs:
      - targets: ["http://192.168.0.105:8080"]
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: victoria-metrics
      client_secret: i1yi2jFvF44bT5Hy68CTjK0TjJAoCkGt
      token_url: http://192.168.0.105:8084/realms/application_keycloak/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials