server:
  port: 8085
spring:
  application:
    name: application-feedback-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://hedgerock:12345@192.168.0.105:8888