product:
  services:
    catalogue:
      uri: http://localhost:8081
    feedback:
      uri: http://localhost:8085

server:
  port: 8083
spring:
  application:
    name: application_customer_app
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: customer-application
          service-host-type: ip
        url: http://localhost:8086
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.105:8084/realms/application_keycloak
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.0.105:8084/realms/application_keycloak
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: customer-app
            client-secret: AD3eiwLcuazWIBvEK1Wl1Q12dntynsj6
            scope:
              - openid
              - view_catalogue
          admin-keycloak:
            provider: keycloak
            client-id: customer-application-metrics-client
            client-secret: FazhMBqws4nnslFM9HkTkD7TvanhoO5l
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://192.168.0.105:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
