server:
  port: 8888
spring:
  application:
    name: application-centralized-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Hedgerock/app_configurations.git
          clone-on-start: true
          default-label: master
          search-paths:
            - '/configs/{application}/{profile}'